### ISSUE TITLE
Exporting stock orders

### ISSUE THREAD

**Issue by cybersiddhu** [dictyBase/Modware-Loader#137]
The export by default should contain the following fields ...
* email of ordering user.
* Date of order
* Strain/Plasmid/Bacterial Id of order. Do not exporting the primary key value of database table.

And any other useful metadata that might be present.

**Comment by biodavidjm** [comment]
### Step 1. SQL statement

The following SQL statement generates:

stock_order_id,  order_date,  item_id,  Item_name,  First_Name,  Last_name, email

```
SELECT so.stock_order_id, so.order_date, sio.item_id, sio.item item_name, 
colleague.first_name, colleague.last_name, email.email 
FROM stock_order so
JOIN stock_item_order sio ON so.stock_order_id=sio.item_id
JOIN colleague ON so.colleague_id=colleague.colleague_no
JOIN coll_email colemail ON colleague.colleague_no=colemail.colleague_no
JOIN email ON colemail.email_no=email.email_no
```
The assumption is that an order must have a colleague and a colleague must have an email address. Is this assumption correct?

cc: @cybersiddhu
