### ISSUE TITLE
This week's papers not being displayed

### ISSUE THREAD

**Issue by rjdodson** [dictyBase/Modware-Loader#166]
Hi Sidd:

Just a quick note to let you know that the script that identifies This week’s new papers does not appear to be working. This week, there are 4 new papers, but the front page still displays 3 papers from several weeks ago. 

Not urgent for me as I can identify these with an SQL query, but of course misleading for those users following this. 

Thanks,
Bob

**Comment by rjdodson** [comment]
Hi Bob,
Yeah i have seen this from time to time, the papers gets in the database, however that list never gets written to the html files.
I haven't nailed down the exact problem. And yes feel free to open an issue in github, in modware loader repository. However,
if it happens to frequently, then have to dig into it.

thanks,
-sidd

**Comment by rjdodson** [comment]
Hi Sidd:

This week there are two new papers which are correctly displayed as This week’s new papers on the front page-I verified with an SQL query. So maybe you fixed this already? 

Thanks,
Bob

**Comment by cybersiddhu** [comment]
Seems to be working for a while.
