### ISSUE TITLE
Plasmids with improper GenBank sequences

### ISSUE THREAD

**Issue by ypandit** [dictyBase/Modware-Loader#64]
- 7 plasmids have sequences in improper GenBank format
  - [pTX-RFPmars ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=112)
  - [pTX-PsA-CFP ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=376)
  - [pPsA-i-alpha-gal & pPSA-Ugus ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=574)
  - [pEcmA0-i-alpha-gal & pEcmA0-Ugus ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=578)
  - [pEcm0-i-alpha-gal & pEcm0-Ugus](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=581)
  - [pIpkA1-OE ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=720)
  - [pPyr56-KO ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=791)

**Comment by jrhrhi** [comment]
> * พลาสมิด 7 ตัวมีลำดับในรูปแบบ GenBank ที่ไม่เหมาะสม
>   
>   * [pTX-RFPmars ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=112)
>   * [pTX-PsA-CFP ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=376)
>   * [pPsA-i-alpha-gal & pPSA-Ugus ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=574)
>   * [pEcmA0-i-alpha-gal & pEcmA0-Ugus ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=578)
>   * [pEcm0-i-alpha-gal & pEcm0-Ugus](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=581)
>   * [pIpkA1-OE ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=720)
>   * [pPyr56-KO ](http://dictybase.org/db/cgi-bin/dictyBase/SC/plasmid_details.pl?id=791)

**Comment by jrhrhi** [comment]
api/references/icons-in-labels.md

>
